### ISSUE TITLE
Can't create new source.

### ISSUE THREAD

**Issue by nmb10** [CivicKnowledge/metaeditor#16]
```python
>>> Source.objects.create(name='test')
django.db.utils.IntegrityError: duplicate key value violates unique constraint "editor_source_pkey" DETAIL:  Key (id)=(11) already exists.
```

**Comment by nmb10** [comment]
This occurs because of manual modification of the `id` field while loading sources with
```bash
python manage.py load_sources
```
command.

There are two solutions:
1. Simple - do not keep ids from sources.csv (assuming the same tree will be created)
2. Hard - fix id increment after sources load. Requires specific sql query for each database (postgresql, sqlite, etc...).

I prefer first solution. What do you think? Do we really need to keep ids from sources.csv?

**Comment by ericbusboom** [comment]
(1) is fine. There is no need to keep the ID numbers, as long as the same tree is created.

**Comment by nmb10** [comment]
requires:
```bash
python manage.py load_sources --delete
```
