### ISSUE TITLE
Lost ability to add new formats and categories. Add "New" to top for form. 

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/metaeditor#17]
Now that the root record isn't shown, there doesn't appear to be a way to add new formats and categories. Add a "New" button to the top of the form that creates a new entry, with the parent defaulting to Root.

**Comment by nmb10** [comment]
There is a way. Click Add child and select empty choice (------) in the parent field. If node creates without parent, it will be added to root children automatically. Anyway I'll add "New" buttons.
