### ISSUE TITLE
Wrap sources

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/metaeditor#21]
The source names in the left-side source list extend into the right-side source edit area. They should be wrapped to stay in their area.

**Comment by nmb10** [comment]
Can you give a screenshot?

**Comment by ericbusboom** [comment]
![screen shot 2015-04-06 at 11 07 36 am](https://cloud.githubusercontent.com/assets/2560782/7009170/2f334458-dc4d-11e4-95e3-e754c683cb3e.png)

**Comment by nmb10** [comment]
Here 90a9be3 I fixed exactly that. Do you use updated code? Maybe you need to clear cache?

**Comment by ericbusboom** [comment]
A shift-reload in the bowser updated it, but now the long strings are behind the right-side form. Id prefer if they wrapped: 

![screen shot 2015-04-06 at 11 33 58 am](https://cloud.githubusercontent.com/assets/2560782/7009707/056cdba8-dc51-11e4-99d5-e93c980c3fae.png)
