### ISSUE TITLE
Add "Check All" Button on Scraping. List file name, Guessed format

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/metaeditor#25]
On the popup that lists the files that can be scraped from a page, add a button that will check all of the files for inclusion. 

Also, as part of the entry for each file, also show: 
  * The last path element of the URL
  * The File format that is guessed from the extension ( issue #24 )

**Comment by nmb10** [comment]
>check all of the files for inclusion

What do you mean by this? What should I really check for? What will happen if user click on "Check all"?

**Comment by ericbusboom** [comment]
Sorry, I mean "Select the checkbox". After pushing the button, all of the checkboxes should have check marks in them. 

> On Apr 7, 2015, at 12:37 AM, Kazbek <notifications@github.com> wrote:
> 
> check all of the files for inclusion
> 
> What do you mean by this? What should I really check for? What will happen if user click on "Check all"?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org
