### ISSUE TITLE
Automatically set Dataset formats from formats of files. 

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/metaeditor#27]
When a dataset is saved, select Format values in the dataset record that are set in the files for the datasets.

**Comment by nmb10** [comment]
But why do we need ability to select format? If user changes formats (without changing datafiles) and submits form, nothing will change. What about disabling or making it read only?

**Comment by ericbusboom** [comment]
There are some cases where the user can't enter files, because they are not available publicly. For instance, you may have to make a special request and sign an agreement. IN that case, there is no URL for the file, but we still want to record what format it would be when we do get it. So, the user has to be able to set formats for the dataset, not just for the files. 

If there are files, from which the formats for the dataset can be inferred, then it is not necessary to have a user editable format on the dataset. If there are no files, then the user must be able to edit dataset formats. 

eric. 

> On Apr 6, 2015, at 11:33 PM, Kazbek <notifications@github.com> wrote:
> 
> But why do we need ability to select format? If user changes formats (without changing datafiles) and submits form, nothing will change. What about disabling or making it read only?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org
