### ISSUE TITLE
Coverage and Region changes

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/metaeditor#31]
Change "Coverage" to "Geo Coverage"

Change "Region" to "Geo Grain"

Set the items in the select list for Geo Grain from a computation made from the geoid package ( in pip ):

    from geoid.civick import GVid
    from geoid import summary_levels
    select_options =  [ (level.title(), str(GVid.get_class(level)().summarize())) for level in summary_levels ]
     
For Geo Coverage, the form field should be an auto complete on place names in the Ambry search system. 

Make metaeditor have a requirement on ambry. The Geo Coverage box becomes a search as you type, where the search term is looked up with similar code to ambry.ui.renderer.place_search(). ( If you run `ambry library doc`, the webserver will have this interface at http://localhost:8085/search/place?term=San%20Die

For the place search to work, you will have to initialize the search system:

    $ ambry library search -R # To index the search system. The places are  fast, bundles take 10 min

Then you can test that you can find things: 

    $ ambry library search -i California

After that, calls to library search system should return results. 

To get a handle on the library:

    import ambry
    l = ambry.library()
    term = 'California'
    results =  [ (name, gvid) for  score, gvid, name in l.search.search_identifiers(term, limit = 30) ]

**Comment by nmb10** [comment]
Couldn't initialize search system.

```bash
$ ambry library search -R
```

Updating the identifier
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/nmb10/.virtualenvs/metaeditor/lib/python2.7/site-packages/ambry/cli/__main__.py", line 7, in <module>
    main(sys.argv)
  File "/home/nmb10/.virtualenvs/metaeditor/local/lib/python2.7/site-packages/ambry/cli/__init__.py", line 360, in main
    f(args, rc)
  File "/home/nmb10/.virtualenvs/metaeditor/local/lib/python2.7/site-packages/ambry/cli/library.py", line 136, in library_command
    globals()['library_'+args.subcommand](args, l,rc)
  File "/home/nmb10/.virtualenvs/metaeditor/local/lib/python2.7/site-packages/ambry/cli/library.py", line 460, in library_search
    p = l.get(source).partition
  File "/home/nmb10/.virtualenvs/metaeditor/local/lib/python2.7/site-packages/ambry/library/__init__.py", line 461, in get
    raise NotFoundError("Failed to resolve reference '{}' in library '{}' ".format(ref, self.database.dsn))
ambry.dbexceptions.NotFoundError: Failed to resolve reference 'civicknowledge.com-terms-geoterms' in library 'sqlite:////home/nmb10/ambry/library.db'

```bash
$ ambry info
```
Version:  0.3.601, development
Root dir: /home/nmb10/ambry
Source :  /home/nmb10/ambry/source
Configs:  ['/home/nmb10/.ambry.yaml', '/home/nmb10/.ambry-accounts.yaml']

```bash
$ ambry library info
````
Library Info
Name:      default
Database:  sqlite:////home/nmb10/ambry/library.db
Cache:     /home/nmb10/ambry/library
Doc Cache: <bound method DocCache.cache of <ambry.library.doccache.DocCache object at 0xb665d08c>>
Whs Cache: /home/nmb10/ambry/warehouses
Remotes:   HttpCache: url=http://s3.sandiegodata.org/library/

**Comment by nmb10** [comment]
I did it without ambry search, so if it's the bug of the ambry I can create it there and close that issue.
