### ISSUE TITLE
Get a number from Number Server for all Datasets. 

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/metaeditor#34]
Ambry has a number server that doles out unique numbers. It is called when creating new bundles, in ambry.cli.source.source_new()

Add a field to the dataset model called "vid" and when a new dataset is created, get it a number from the server. 

The number should be user editable in the dataset form. 

```
from ambry.run import  get_runconfig
from ..identity import NumberServer

rc = get_runconfig()
nsconfig = rc.service('numbers')
ns = NumberServer(**nsconfig)
id_number_as_string = str(ns.next())
```

**Comment by nmb10** [comment]
Requires migration.

**Comment by ericbusboom** [comment]
ERROR Coverages search failed with `too many values to unpack` error.
