### ISSUE TITLE
IndexError at /editor/sources/: list index out of range

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/metaeditor#4]
Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/editor/sources/

Django Version: 1.7.1
Python Version: 2.7.6
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'mptt',
 'editor')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/Library/Python/2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/eric/proj/metaeditor/editor/views.py" in sources
  38.     root = Source.objects.filter(level=0)[0]
File "/Library/Python/2.7/site-packages/django/db/models/query.py" in __getitem__
  177.         return list(qs)[0]

Exception Type: IndexError at /editor/sources/
Exception Value: list index out of range

**Comment by Pthinker** [comment]
Please add some records in admin page first

**Comment by ericbusboom** [comment]
> On Feb 24, 2015, at 10:57 AM, David Zhang <notifications@github.com> wrote:
> 
> Please add some records in admin page first

I can't. Adding sources requires a parent, and the first source added has no parent, so the admin page throws an error. 

I can add Categories OK. 

There used to be a migration that added the root for sources. 

eric. 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org

**Comment by Pthinker** [comment]
I already removed the requirement for that so you can add source/format/category in admin no matter there is record or not.

**Comment by ericbusboom** [comment]
> On Feb 24, 2015, at 11:10 AM, David Zhang <notifications@github.com> wrote:
> 
> I already removed the requirement for that so you can add source/format/category in admin no matter there is record or not.

Oh, sorry, I misread which field was throwing the error. 

eric. 

----------------------------------------------------------------------------------------------------------
Eric Busboom                                                                                (619) 363 2607        
eric@busboom.org                                                         http://www.busboom.org
