### ISSUE TITLE
Automatically create root nodes

### ISSUE THREAD

**Issue by ericbusboom** [CivicKnowledge/metaeditor#8]
Automatically create the root nodes for all of the hierarchies. Remove the option to create the roots. Remove the root  from the tree display ( just don't show it ) since it is not necessary to see.

**Comment by nmb10** [comment]
How should I name root nodes?

**Comment by ericbusboom** [comment]
Just call them “Root” or “-“ It doesn’t really matter. 

eric.

**Comment by nmb10** [comment]
Waiting for #16 .

**Comment by nmb10** [comment]
Create root nodes for Source, Format and Category with:
```bash
python manage.py create_roots
```

Note: sources should be imported before that run.
